language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: kqIZF3RguqSMuG5iGMKLkFFtAx1n98vD6+o0MQjWNjskEMM+yDApGMw97ejM0S31ka3JO+UpSDGuVakYtr4r/YI8f/Ez+KugDX1/1gL9rkIflicdnUULSzhJsvwXtQnCt9Zehm9TK31lFsV5i5G0lsPNo6Ry2I7H/YJe1Av6/KUNMHBKB335GL0hlvdJvGkAAKuKg0asMstKnXM210/3MTfDij+irbYXRWmtaxxLkEwldCD7o8WmkNZep+2LN1NwWTFN7roDfhCJ8XmExPY5gjpwGN7+x/qEJEgdtzkdQO+fRU3O6LpcmF3yazHo1R1huYQF5DF7Csn18chLC4BIovA0raKmiqCMABqSL1ajLXfbl0GmzIx9gTKon+5bBn0x954ZDg3s9+v0JdO15IsntVNM/7SWg9/NzzV1zwj6LYNcSehS7Mm13eC5tOc2d5wlRfWIoI7+UYQ9ec1JHkzYRRl1bM0TtSwicFTeuvUkHDdecgU2Bi1kdpWgbU9bxsQL64ceyMY4T5suODjtllOiWS5WNeKAx0uAuFhK7UhT76jdFyfw70cbVJN0YE40sC3P3IMxyWrWJswfnpNNuJajsK+HSUc+jOJ0Vs0EHNT/fJ888+bEeqJ+ddxunHpBbYnXS0kOcYhrQgYJHTBlA1JC1ird9X4Us2LU6FwStsTwx84=
  on:
    tags: true
    repo: mathroule/cellartracker
    python: 3.8
