language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  uuser: __token__
  password:
    secure: LX7Pj5n9uc728L8vnnzQX+DG+eQNiIg/2RHNA0oxZe+zGbogRAEt/sVU88dNwu0K0+AJEPXYLxZ05jlPhpgz5QcaU6IUl/0K+9n3AfB59PRJrVBArCexkxy3vxOOYECN7H2B0/01j+FaK95YvkXZxaZtALsLEkGfWDm9xI7mU0yG29uMJ35ti89y/jePTN0A+NGySf8bfislGnPAO8V8UTQsEH0QLRZSlaqxo2eDmpZD9b0oC9U+YAMbetN5jQ1MLTk430dv6cL3lZkR4lIigCLRl32yiqieI8RVglo2cZTHeSj0lyw6zbQp6H9cSnyQBypZj9z/f1yhYL4fYRuBjyE4u2IgR/m9hXGFN+HZkdbbkeaIOPZOQvcZyJGFBQb23LbL0471+qrK94GqYcs1B14LgzBYhbyJN1FYFbVCaeBp4xxWkOvHkC36h/Gm1mzlRpWXccnY1rMjGpMGaC/UgFRov3jwcT1cHwTckV72O4SoXck50e/ZX3me2gcrB+ZOW+r49vwKg2Seh6TqATjxjvT/80vvQcbCMNCTjSVe5BldNi0NOkSoy4eb17jIm24eiEF1yjvqRVhmboGLS0mmSRCSAT6fF0r64kdBMhghDWEqF9SsUNuQe7WX6zh4nRjNQOYe6Q8qf6DSDG0oY1BTR52pOYEgJHFvUgCjgz8zkZY=
  on:
    tags: true
    repo: mathroule/cellartracker
    python: 3.8
