language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  uuser: "__token__"
  password:
    secure: FwmFyRMYgcKUHGMoXFkVZPNRjHT+l8UZepAqOQOLix0hcYOIGs0Ahx9mOEO3ijRQi9fXiu8XWbmdNGFmXsXm6M9sw838xTJk+ZJlq2eg7nd8Jn6ZLRN0J+3mFboDZQO8dLj98byzroSNRG2QgTp1kSBF7GdinDxQY1Ac9gPcbTnky+YxwF6cndWs3V+irXIS0+G43nUu4TfW81Q7QPbpIjlO8jY+1TCbFRnHcnjdMgq2ruNIJqHzGzY6lcU5xWFh0ULdzLqs9KyQM7OfY7bYaoDfOVvkQbggChUmqK21ccf/kmgflC3xEh0YXmbfhi/pzbOX5hR5ALE2TH6gVJP9pYp0AdRrWyDkVljTtEhPtn4X+Pe7FldNxzcAoDW0/KR+x2Hhr0yLfbiTAs1KNOsKOGsKuhmSahAIULbKO5hlz2KpebeiJMTXZ2ihVQCGaS3wjW9RixdSA9MVLWViZCIY+LwXOiYU03P52bWvESDOwGPLOFzD0M7V1oEPxo2IuQeXnBh7aJWkpmGNkiCF49K6iOPbI3FUCFwSH66FE01SCnTetpSDvb4E6rz1YekaPi4REmvTr8U4FP21OTH0LMjC8CKPuvVPHRVtMIHVq5jl0lTR5iaHd3BCUH0ugP97eKi34ZGyRWlCJa3N3QNeLGEK+izxUgfS0tLz1+GHv7izGvA=
  on:
    tags: true
    repo: mathroule/cellartracker
    python: 3.8
