language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: KjqRYLOJTEGZ9+iiF/eU6tmrsVhdzTazmgSaumDkTqbw5hq7CIQYmB5+OV/N4xoI/yMaoAXTFg+sUL3SR+7MjH7k8wFUOzfr0+Kkij+aWJj7lFPspfweYbNROy4vFFvJE9EJK4PHn6krCBYeF4T6aQTBHK6dCAhTGLTekLTmYcYg6SUkgGR/RAuYCVwoSKL9YYENaNAZNTQTUfo4U955qaRRBFIWEDVB7tDBLbGSwRYUCbnAmEXyhUMftjirzX1h4n7aQRk+xBFcdwWbSuRMuVcPRYGz1Kyn3BS+pCJB7OwqoQsHWETpbNf+wfmRj/bZYGSwKC1uH3aRHCIM3HEIK721QdWjqqzVwkogJQhjUz2LAacr22eAustFY/QcKXtaHnPnCjxY6rbpoVuLwJETe+YA987sfoRtONS1O2x0Mx6aHe4qlYG78olXu5nh24s0S8OBtAIF69fCDPx7cBZMWbSQcEwGMkoayLg9VpXGFVwzkGPRIEbE72bb8mCRG06WOi3HXc6Nbn1NFbzxTITnsKQtoCUtyEiTvzPST1WXpLq22JAlP9jzy6PBu9kgL9OsrMWTe0xNZJWGrewvCclX07UeOD95GS1CCnZT1P3h8OaV8cX16H8qM59ahxDRCPioa9nat4tKBEC4gSFJ9YjnXZG95b6dyFEUiJZ1+iR9dos=
  on:
    tags: true
    repo: mathroule/cellartracker
    python: 3.8
